/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ["class"],
    content: ["./src/**/*.{js,jsx,ts,tsx,css}"],
    safelist: [
        'bg-brand-blue',
        'text-brand-blue',
        'bg-brand-gold',
        'text-brand-gold',
        'bg-brand-cream',
        'text-brand-cream',
        'hover:bg-brand-cream',
        'hover:text-brand-cream',
        'border-brand-blue',
        'border-brand-gold',
        'border-brand-cream',
        'bg-white',
        'bg-red-50/50',
        'border-red-500',
        'border-yellow-500',
        'border-green-500',
        'border-gray-300',
        'border-transparent',
        'border-[#1e3a8a]',
        'bg-[#1e3a8a]',
        'bg-[#ffd7ba]/10',
        'bg-[#ffd7ba]/20',
        'hover:bg-[#ffd7ba]/20',
        'hover:shadow-[0_2px_8px_rgba(0,0,0,0.1)]',
        'shadow-[0_2px_8px_rgba(0,0,0,0.15)]',
        'text-gray-900',
        'text-gray-500',
        'text-red-500'
    ],
    theme: {
        container: {
            center: true,
            padding: "2rem",
            screens: {
                "2xl": "1400px",
            },
        },
        extend: {
            colors: {
                'brand-blue': '#0066CC',
                'brand-blue-dark': '#0F1C2E',
                'brand-blue-light': '#E6F0FA',
                'brand-gold': '#D4AF37',
                'brand-gold-light': '#F7F3E3',
                'brand-navy': '#0F1C2E',
                'brand-red': '#EF4444',
                'neutral-100': '#F5F7FA',
                'neutral-200': '#EEF2F6',
                'neutral-300': '#E4E9F0',
                'neutral-400': '#D1DAE6',
                'neutral-500': '#9EABC4',
                'neutral-600': '#6B7A95',
                'neutral-700': '#4A5568',
                'neutral-800': '#2D3748',
                'neutral-900': '#1A202C',
            },
            fontFamily: {
                heading: ['Merriweather', 'serif'],
                body: ['Inter', 'sans-serif'],
            },
            borderRadius: {
                'sm': '0.25rem',
                'md': '0.5rem',
                'DEFAULT': '0.5rem',
                'lg': '0.75rem',
                'xl': '1rem',
                '2xl': '1.5rem',
                'full': '9999px',
            },
            boxShadow: {
                'sm': '0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.08)',
                'md': '0 4px 6px rgba(0, 0, 0, 0.1), 0 2px 4px rgba(0, 0, 0, 0.06)',
                'DEFAULT': '0 4px 6px rgba(0, 0, 0, 0.1), 0 2px 4px rgba(0, 0, 0, 0.06)',
                'lg': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
                'xl': '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
                '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
                'inner': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.05)',
                'none': 'none',
            },
            keyframes: {
                "accordion-down": {
                    from: { height: "0" },
                    to: { height: "var(--radix-accordion-content-height)" },
                },
                "accordion-up": {
                    from: { height: "var(--radix-accordion-content-height)" },
                    to: { height: "0" },
                },
                fadeIn: {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
                'fadeIn': 'fadeIn 0.2s ease-in-out',
            },
        },
    },
    plugins: [
        require('@tailwindcss/typography'),
        require('@tailwindcss/forms'),
    ],
};